version: '3.9'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: employee
      MYSQL_USER: shreyas
      MYSQL_PASSWORD: shreyas123
    ports:
      - "3306:3306"
   

  springboot-docker-container:
    image: shreyasphuke/springboot-image:v1
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: springboot-docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql-standalone
